---
# PLEASE USE kubectl create secret docker-registry regcred --docker-server=registry.gitlab.com --docker-username=<your-name> --docker-password=<token>
#apiVersion: v1
#kind: Secret
#metadata:
#  name: regcred
#  namespace: default
#type: kubernetes.io/dockerconfigjson
#data:
#  .dockerconfigjson: <base64 encoded .docker/config>
#stringData:
#  docker-server: registry.gitlab.com
#  docker-username: yourUsername
#  docker-password: yourToken
#data:
#  docker-server: registry.gitlab.com
#  # Encode username with: echo "yourUsername" | base64
#  # Test encryption with: echo "encodedUsername" | base64 -d
#  docker-username: encodedUsername
#  # Encode username with: echo "yourToken" | base64
#  # Test encryption with: echo "encodedToken" | base64 -d
#  docker-password: encodedToken
